{% set name = "popfinder" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/popfinder-{{ version }}.tar.gz
  sha256: 92749564daafe2d982c0bb56cfa38e89edd889239761f402def317bfcd1102c1

build:
  number: 0
  noarch: python
  entry_points:
    - "pop_classifier = popfinder.cli_classifier:main"
    - "pop_regressor = popfinder.cli_regressor:main"
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - pandas
    - numpy
    - scikit-learn
    - dill
    - seaborn
    - matplotlib-base
    - scikit-allel
    - zarr
    - h5py
    - scipy

test:
  imports:
    - popfinder
    - tests
  commands:
    - pip check
  requires:
    - pip
    - pytest

about:
  home: https://syncrosim.com/
  summary: Genetic population assignment using neural networks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - katieb1
